=== APlusMalware/FCE-Translation-Plugin/APlusMalware.FceTranslationPlugin/Translations.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="ArrayOfTranslation" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
  <xs:element name="ArrayOfTranslation" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Translation">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Old" type="xs:string" minOccurs="0" />
              <xs:element name="New" type="xs:string" minOccurs="0" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== APlusMalware/FCE-Translation-Plugin/APlusMalware.FceTranslationPlugin/Translations.xml
<?xml version="1.0" encoding="utf-8" ?>
<ArrayOfTranslation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="Translations.xsd">
  <Translation>
    <!--
    &#xA; is the escape sequence for newline characters.
    Old text must be an exact character-for-character match. Find strings with a decompiler or disassembler.
    The new text should not be longer than the old; any extra characters are ignored (UTF-16 encoded).
    -->
    <Old>&#xA;Press E to configure</Old>
    <New>&#xA;Don't press E.</New>
  </Translation>
  <Translation>
    <Old>&#xA;(Home) Raise Lift.</Old>
    <New>&#xA;(Home) Go Higher.</New>
  </Translation>
  <Translation>
    <Old>&#xA;Keeps charge when picked up&#xA;Press 'Shift+E' to light fuse</Old>
    <New>&#xA;Keeps charge when broken&#xA;Press 'Shift+E' to SUPER-charge!</New>
  </Translation>
</ArrayOfTranslation>
